# Generated by Django 4.1.7 on 2023-06-30 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=15)),
                ('hostname', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=1500)),
                ('request_params', models.JSONField(blank=True, default=None, null=True)),
                ('client_ip', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, default=None, max_length=1500, null=True)),
                ('response_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('request_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
