# Generated by Django 5.1 on 2024-11-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_logging", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestlog",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="requestlog",
            name="headers",
            field=models.JSONField(default=dict),
        ),
    ]
